import { createContext, useContext, useState, ReactNode } from "react";

type Language = "en" | "de" | "kr";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Navigation
    "nav.about": "ABOUT",
    "nav.menu": "MENU",
    "nav.contact": "CONTACT",
    
    // Home page
    "home.aboutUs": "About us",
    "home.aboutText": "In our characteristic takeaway space and decorated inn, \"Hankki\" ultra indulges the fans, which carries 500 types and natural relationship takeaway upon one line line. We pride ourselves on serving the finest Korean fried chicken in Jakarta.",
    "home.menu": "Menu",
    "home.chicken": "Chicken",
    "home.chickenDesc": "In our characteristic takeaway space and decorated inn, there are more than couple. We are here to eat delicious fried chicken. Some text describing the chicken which has great variety or style can fill in be be.",
    "home.goToMenu": "Go to menu →",
    "home.openingHours": "Opening Hours",
    "home.weekday": "Weekday",
    "home.closed": "Closed",
    "home.contact": "Contact",
    "home.makeReservation": "Make a reservation →",
    "home.hero.title": "HANKKI",
    "home.hero.subtitle": "Korean Fried Chicken",
    "home.hero.description": "Experience authentic Korean flavors in the heart of Cologne",
    "home.menu.item1.name": "Original Fried Chicken",
    "home.menu.item1.desc": "Crispy golden fried chicken with our signature Korean spices. Perfectly seasoned and fried to perfection.",
    "home.menu.item2.name": "Spicy Korean Wings",
    "home.menu.item2.desc": "Succulent chicken wings glazed with our house special gochujang sauce. A fan favorite!",
    "home.menu.item3.name": "Honey Garlic Chicken",
    "home.menu.item3.desc": "Sweet and savory chicken pieces coated in our signature honey garlic glaze.",
    "home.kitchenUntil": "Kitchen until",
    
    // About page
    "about.title": "About Us",
    "about.ourStory": "Our Story",
    "about.storyText": "In our characteristic takeaway space and decorated inn, \"Hankki\" ultra indulges the fans, which carries 500 types and natural relationship takeaway upon one line line. We pride ourselves on serving the finest Korean fried chicken in Cologne. Our recipes have been perfected over years, combining traditional Korean cooking techniques with locally sourced ingredients to create a unique dining experience.",
    "about.ourValues": "Our Values",
    "about.value1Title": "Quality",
    "about.value1Text": "We use only the finest ingredients and maintain the highest standards in every dish we serve.",
    "about.value2Title": "Passion",
    "about.value2Text": "Our love for Korean cuisine drives us to perfect every recipe and create memorable dining experiences.",
    "about.value3Title": "Community",
    "about.value3Text": "We believe in building lasting relationships with our customers and being part of the local community.",
    "about.hansikTitle": "Korean Traditional Cuisine",
    "about.hansikText": "Hansik represents the traditional food culture of Korea, emphasizing balanced nutrition and harmony. Our dishes are inspired by this centuries-old culinary tradition, bringing authentic Korean flavors to Cologne. From our signature fried chicken to traditional side dishes, every element is crafted with respect for Korean culinary heritage.",
    "about.teamTitle": "Our Team",
    "about.teamText": "Our team is a passionate group of food lovers dedicated to bringing the best of Korean cuisine to our customers. From our skilled chefs who craft each dish with care to our friendly staff who ensure a welcoming dining experience, we are committed to excellence in everything we do. Meet the people behind Hankki and discover the passion that drives us to serve delicious Korean fried chicken and more.",

    // Menu page
    "menu.title": "Menu",
    "menu.categories.all": "All",
    "menu.categories.stew": "Stew",
    "menu.categories.soup": "Soup",
    "menu.categories.bulgogi": "Bulgogi",
    "menu.categories.chicken": "Chicken",
    "menu.categories.friedChicken": "Fried Chicken",
    "menu.categories.noodle": "Noodle",
    "menu.categories.bibimbap": "Bibimbap",
    "menu.categories.streetfood": "Streetfood",
    "menu.categories.pancake": "Pancake",
    "menu.categories.side": "Sides",
    "menu.categories.drinks": "Drinks",
    "menu.categories.extra": "Extras",
    "menu.extra": "Custom Extras",
    "menu.included": "Included",

    // Menu items
    "menu.items.budaeJjigae": "Budae Jjigae",
    "menu.items.budaeJjigaeDesc": "Spicy stew with sausages, pork meat, ramyun noodles and vegetables",
    "menu.items.budaeJjigae.included": "2 bowls of rice included",
    "menu.items.budaeJjigae.extra": "Add ramyun pieces +2€",
    "menu.items.bulgogijeongol": "Bulgogi Jeongol",
    "menu.items.bulgogijeongolDesc": "Savory beef stew with vegetables andmushrooms, based on a soy sauce broth",
    "menu.items.bulgogijeongol.included": "2 bowls of rice included",
    "menu.items.dakgalbi": "Dakgalbi",
    "menu.items.dakgalbiDesc": "Spicy stir-fried chicken with vegetables and rice cakes",
    "menu.items.dakgalbi.included": "2 bowls of rice included",
    "menu.items.dakgalbi.extra": "Extra Cheese +3€",
    "menu.items.gochujangBulgogi": "Gochujang-Bulgogi",
    "menu.items.gochujangBulgogiDesc": "Stir-fried pork in spicy marinade",
    "menu.items.ganjangDoejiBulgogi": "Ganjang Doeji Bulgogi",
    "menu.items.ganjangDoejiBulgogiDesc": "Stir-fried pork in hearty soy sauce marinade",
    "menu.items.Bulgogi": "Bulgogi",
    "menu.items.BulgogiDesc": "Stir-fried beef in soy sauce marinade",
    "menu.items.cheeseBuldak": "Cheese Buldak",
    "menu.items.cheeseBuldakDesc": "Cheesy spicy marinated stir-fried chicken",
    "menu.items.jjimDak": "Jjim-Dak",
    "menu.items.jjimDakDesc": "Steamed chicken marinated in soy sauce",
    "menu.items.japchae": "Japche",
    "menu.items.japchaeDesc": "Stir-fried glass noodles with vegetables",
    "menu.items.japchae.sub.beef": "Beef",
    "menu.items.japchae.sub.mushroom": "Mushroom",
    "menu.items.kimchiJjigae.sub.porkTofu": "Pork and Tofu",
    "menu.items.kimchiJjigae.sub.porkOnly": "Pork Only",
    "menu.items.kimchiJjigae.sub.tofuOnly": "Tofu Only",
    "menu.items.kimchiJjigae": "Kimchi Jjigae",
    "menu.items.kimchiJjigaeDesc": "Spicy stew made with kimchi",
    "menu.items.Doenjang-Jjigae": "Doenjang Jjigae",
    "menu.items.Doenjang-JjigaeDesc": "Stew with aged soybean paste, tofu and vegetables",
    "menu.items.Doenjang-Jjigae.sub.Vegetables": "Vegetables",
    "menu.items.Doenjang-Jjigae.sub.Seafood": "Seafood",
    "menu.items.Odeng-Tang": "Odeng Tang",
    "menu.items.Odeng-TangDesc": "Warm soup with fish cakes and vegetables in aclear, savory broth",
    "menu.items.Dolsot-Bibimbap": "Dolsot Bibimbap",
    "menu.items.Dolsot-BibimbapDesc": "Rice with beef and a variety of vegetables in a hot stone pot",
    "menu.items.Dubu-Bibimbap": "Dubu Bibimbap",
    "menu.items.Dubu-BibimbapDesc": "Rice with Tofu and a variety of vegetables in a hot stone pot",
    "menu.items.Beosot-Bibimbap": "Beosot Bibimbap",
    "menu.items.Beosot-BibimbapDesc": "Rice with mushrooms and a variety ofvegetables in a hot stone pot",
    "menu.items.Extra.Beef": "Extra Beef +2.0€",
    "menu.items.Extra.TofuMush": "Extra Tofu and Mushroom +1.5€",
    "menu.items.Extra.Egg": "Extra Egg +1.0€",
    "menu.items.Gomtang": "Gomtang",
    "menu.items.GomtangDesc": "Beef bouillon with tender and soft boiled beef slices and glass noodles",
    "menu.items.Yukgaejang": "Yukgaejang",
    "menu.items.YukgaejangDesc": "Spicy stew with beef and vegetables",
    "menu.items.Ddeokbokki": "Ddeokbokki",
    "menu.items.DdeokbokkiDesc": "Spicy stir-fried rice cakes with fishcakes and vegetables",
    "menu.items.Cheese-Ddeokbokki": "Cheese Ddeokbokki",
    "menu.items.Cheese-DdeokbokkiDesc": "Spicy stir-fried rice cakes with fish cakes, vegetables and melted cheese",
    "menu.items.Jjajang-Ddeokbokki": "Jjajang-Ddeokbokki",
    "menu.items.Jjajang-DdeokbokkiDesc": "Stir-fried rice cakes with black beansauce, beef, fish cakes, and vegetables",
    "menu.items.Gun-Mandu": "Gun-Mandu",
    "menu.items.Gun-ManduDesc": "Fried dumplings filled with vegetables",
    "menu.items.Kimchi-Jeon": "Kimchi-Jeon",
    "menu.items.Kimchi-JeonDesc": "Spicy pancakes with aged Kimchi",
    "menu.items.Pajeon": "Pajeon",
    "menu.items.PajeonDesc": "Korean pancake with spring onions",
    "menu.items.pajeon.sub.seafood": "Seafood",
    "menu.items.pajeon.sub.mushroom": "Mushroom",
    "menu.items.Kimchi": "Kimchi",
    "menu.items.KimchiDesc": "Spicy Korean-style pickled cabbage",
    "menu.items.ExtraRice": "Extra Rice",
    "menu.items.ExtraFriedChickenSauce": "Extra Fried Chicken Sauce",
    "menu.items.ExtraFriedChickenSauceDesc": "sauce for Fried Chicken (Yangnyeom / Ganjang)",
    "menu.items.ExtraColeslaw": "Extra Coleslaw",
    "menu.items.ExtraSauces": "Extra Sauces",
    "menu.items.ExtraSaucesDesc": "sauces (soy sauce, chili paste, mayonnaise, salad dressing)",
    "menu.items.ExtraCheese": "Extra Cheese",
    "menu.items.ExtraPickledRadish": "Extra Pickled Radish",
    "menu.items.ExtraSideDishes": "Extra Side Dishes",



    "menu.findUs": "Find us",
    "menu.filters": "Filters",
    "menu.dietaryPreferences": "Dietary Preferences",
    "menu.all": "All",
    "menu.vegetarian": "Vegetarian",
    "menu.nonVegetarian": "Non-Vegetarian",
    "menu.spicinessLevel": "Maximum Spiciness Level",
    "menu.allLevels": "All Levels",
    "menu.notSpicy": "Not Spicy",
    "menu.mild": "Mild",
    "menu.medium": "Medium",
    "menu.hot": "Hot",
    "menu.spiciness": "Spiciness",
    "menu.allergens": "Allergens",
    
    "menu.guide.title": "Ordering Guide",
    "menu.guide.hover": "Learn how to order Hankki chicken",
    "menu.guide.step1.title": "1. Choose Your Style",
    "menu.guide.step1.desc": "Choose between our classic bone-in chicken or convenient boneless pieces.",
    "menu.guide.step2.title": "2. Choose Your Size",
    "menu.guide.step2.desc": "Select M for a half chicken, perfect for one person, or L for a whole chicken, great for sharing.",
    "menu.guide.step3.title": "3. Choose Your Configuration",
    "menu.guide.step3.desc": "Opt for 'Whole' to enjoy one flavor across your entire order, or go for 'Half & Half' to mix and match two different flavors in one order.",
    "menu.guide.step4.title": "4. Pick Your Flavor(s)",
    "menu.guide.step4.desc": "Choose from our range of delicious flavors, from classic soy garlic to spicy gochujang. If you selected 'Half & Half', you can pick two different flavors to enjoy the best of both worlds!",

    "menu.downloadPDF": "Download PDF",
    "menu.downloadPDFAlert": "Menu PDF download would start here. In production, this would download the actual menu PDF.",
    
    "menu.openingHours": "Opening Hours",
    "menu.mondayFriday": "Monday - Friday",
    "menu.saturdaySunday": "Saturday - Sunday",
    
    // Contact page
    "contact.title": "Contact",
    "contact.getInTouch": "Get in Touch",
    "contact.address": "Address",
    "contact.email": "Email",
    "contact.phone": "Phone",
    "contact.followUs": "Follow Us",
    "contact.reservation": "Reservation Request",
    "contact.name": "Full Name",
    "contact.phoneNumber": "Phone Number",
    "contact.emailAddress": "Email Address",
    "contact.numberOfGuests": "Number of Guests",
    "contact.dateTime": "Date & Time",
    "contact.date": "Date",
    "contact.time": "Time",
    "contact.mondayClosed": "Monday closed",
    "contact.selectTime": "Select time",
    "contact.submit": "Submit Reservation Request",
    "contact.submitAlert": "Your reservation request has been received. We will check availability and get back to you as soon as possible.",
    "contact.required": "* All fields are required",
    "contact.alert":"⚠️ Same-day reservations are not possible online!",
    "contact.selectGuests": "Select guests",
    "contact.guest": "Guest",
    "contact.guestsPlural": "Guests",
    "contact.namePlaceholder": "Enter your name",
    "contact.phonePlaceholder": "+62 xxx xxxx xxxx",
    "contact.emailPlaceholder": "your.email@example.com",
    
    // Footer
    "footer.tagline": "Come try our about your company here",
    
    // Days
    "days.tuesday": "Tuesday",
    "days.friday": "Friday",
    "days.saturday": "Saturday",
    "days.sunday": "Sunday",
    "days.monday": "Monday",
  },
  de: {
    // Navigation
    "nav.about": "ÜBER UNS",
    "nav.menu": "SPEISEKARTE",
    "nav.contact": "KONTAKT",
    
    // Home page
    "home.aboutUs": "Über uns",
    "home.aboutText": "In unserem charakteristischen Takeaway-Raum und dekorierten Gasthaus verwöhnt \"Hankki\" die Fans mit über 500 Sorten. Wir sind stolz darauf, das beste koreanische Brathähnchen in Jakarta zu servieren.",
    "home.menu": "Speisekarte",
    "home.chicken": "Hähnchen",
    "home.chickenDesc": "In unserem charakteristischen Takeaway-Raum gibt es mehr als ein paar. Wir sind hier, um köstliches Brathähnchen zu essen. Ein Text, der das Hähnchen beschreibt, das eine große Vielfalt oder einen großen Stil hat.",
    "home.goToMenu": "Zur Speisekarte →",
    "home.openingHours": "Öffnungszeiten",
    "home.weekday": "Wochentag",
    "home.closed": "Geschlossen",
    "home.contact": "Kontakt",
    "home.makeReservation": "Reservierung vornehmen →",
    "home.hero.title": "HANKKI",
    "home.hero.subtitle": "Korean Fried Chicken",
    "home.hero.description": "Experience authentic Korean flavors in the heart of Cologne",
    "home.menu.item1.name": "Original Fried Chicken",
    "home.menu.item1.desc": "Crispy golden fried chicken with our signature Korean spices. Perfectly seasoned and fried to perfection.",
    "home.menu.item2.name": "Spicy Korean Wings",
    "home.menu.item2.desc": "Succulent chicken wings glazed with our house special gochujang sauce. A fan favorite!",
    "home.menu.item3.name": "Honey Garlic Chicken",
    "home.menu.item3.desc": "Sweet and savory chicken pieces coated in our signature honey garlic glaze.",
    "home.kitchenUntil": "Kitchen until",
    
    // About page
    "about.title": "Über Uns",
    "about.ourStory": "Unsere Geschichte",
    "about.storyText": "In unserem charakteristischen Takeaway-Raum und dekorierten Gasthaus verwöhnt \"Hankki\" die Fans mit über 500 Sorten und natürlicher Beziehung. Wir sind stolz darauf, das beste koreanische Brathähnchen in Köln zu servieren. Unsere Rezepte wurden über Jahre perfektioniert und kombinieren traditionelle koreanische Kochtechniken mit lokalen Zutaten.",
    "about.ourValues": "Unsere Werte",
    "about.value1Title": "Qualität",
    "about.value1Text": "Wir verwenden nur die besten Zutaten und halten die höchsten Standards in jedem Gericht ein.",
    "about.value2Title": "Leidenschaft",
    "about.value2Text": "Unsere Liebe zur koreanischen Küche treibt uns an, jedes Rezept zu perfektionieren.",
    "about.value3Title": "Gemeinschaft",
    "about.value3Text": "Wir glauben daran, dauerhafte Beziehungen zu unseren Kunden aufzubauen.",
    "about.hansikTitle": "Traditionelle Koreanische Küche",
    "about.hansikText": "Hansik repräsentiert die traditionelle Esskultur Koreas und betont ausgewogene Ernährung und Harmonie. Unsere Gerichte sind von dieser jahrhundertealten kulinarischen Tradition inspiriert und bringen authentische koreanische Aromen nach Köln.",
    "about.teamTitle": "Unser Team",
    "about.teamText": "Unser Team ist eine leidenschaftliche Gruppe von Feinschmeckern, die sich der Aufgabe verschrieben haben, das Beste der koreanischen Küche zu unseren Kunden zu bringen. Von unseren talentierten Köchen, die jedes Gericht mit Sorgfalt zubereiten, bis hin zu unserem freundlichen Personal, das für ein einladendes Esserlebnis sorgt, setzen wir uns in allem, was wir tun, für Exzellenz ein. Lernen Sie die Menschen hinter Hankki kennen und entdecken Sie die Leidenschaft, die uns antreibt, köstliches koreanisches Brathähnchen und mehr zu servieren.",

    // Menu page
    "menu.title": "Speisekarte",
    "menu.categories.all": "Alle",
    "menu.categories.stew": "Stew",
    "menu.categories.soup": "Suppe",
    "menu.categories.bulgogi": "Bulgogi",
    "menu.categories.chicken": "Hähnchen",
    "menu.categories.friedChicken": "Brathähnchen",
    "menu.categories.noodle": "Nudeln",
    "menu.categories.bibimbap": "Bibimbap",
    "menu.categories.streetfood": "Streetfood",
    "menu.categories.pancake": "Pfannkuchen",
    "menu.categories.side": "Beilagen",
    "menu.categories.drinks": "Getränke",
    "menu.categories.extra": "Extras",
    "menu.extra": "Individuelle Extras",
    "menu.included": "Inklusive",

    // Menu items
    "menu.items.budaeJjigae": "Budae Jjigae",
    "menu.items.budaeJjigaeDesc": "Scharfer Eintopf mit Würstchen, Schweinefleisch, Ramyun-Nudeln und Gemüse",
    "menu.items.budaeJjigae.included": "2 Schalen Reis inklusive",
    "menu.items.budaeJjigae.extra": "Ramenstücke hinzufügen +2€",
    "menu.items.bulgogijeongol": "Bulgogi Jeongol",
    "menu.items.bulgogijeongolDesc": "Deftiger Rindereintopf mit Gemüseund Pilzen in Sojasoßenbrühe",
    "menu.items.bulgogijeongol.included": "2 Schalen Reis inklusive",
    "menu.items.dakgalbi": "Dakgalbi",
    "menu.items.dakgalbiDesc": "Deftiger Rindereintopf mit Gemüse und Pilzen in Sojasoßenbrühe",
    "menu.items.dakgalbi.included": "2 Schalen Reis inklusive",
    "menu.items.dakgalbi.extra": "Extra Käse +3€",
    "menu.items.gochujangBulgogi": "Gochujang-Bulgogi",
    "menu.items.gochujangBulgogiDesc": "Gebratenes Schweinefleisch in scharfer Marinade",
    "menu.items.ganjangDoejiBulgogi": "Ganjang Doeji Bulgogi",
    "menu.items.ganjangDoejiBulgogiDesc": "Gebratenes Schweinefleisch inherzhafter Marinade mit Sojasoße",
    "menu.items.Bulgogi": "Bulgogi",
    "menu.items.BulgogiDesc": "Gebratenes Rindfleisch in Sojasoßenmarinade",
    "menu.items.cheeseBuldak": "Cheese Buldak",
    "menu.items.cheeseBuldakDesc": "Gebratene Hähnchenkeulenstücke in scharfer Marinade und Käse",
    "menu.items.jjimDak": "Jjim-Dak",
    "menu.items.jjimDakDesc": "Dampfgebratene Hähnchenstücke in Sojasoßenmarinade",
    "menu.items.japchae": "Japche",
    "menu.items.japchaeDesc": "Gebratene Glasnudeln mit Gemüse",
    "menu.items.japchae.sub.beef": "Rindfleisch",
    "menu.items.japchae.sub.mushroom": "Pilze",
    "menu.items.kimchiJjigae.sub.porkTofu": "Schweinefleisch und Tofu",
    "menu.items.kimchiJjigae.sub.porkOnly": "Nur Schweinefleisch",
    "menu.items.kimchiJjigae.sub.tofuOnly": "Nur Tofu",
    "menu.items.kimchiJjigae": "Kimchi Jjigae",
    "menu.items.kimchiJjigaeDesc": "Scharfer Eintopf mit Kimchi",
    "menu.items.Doenjang-Jjigae": "Doenjang Jjigae",
    "menu.items.Doenjang-JjigaeDesc": "Eintopf mit fermentierter Sojabohnenpaste, Tofu und Gemüse",
    "menu.items.Doenjang-Jjigae.sub.Vegetables": "Gemüse",
    "menu.items.Doenjang-Jjigae.sub.Seafood": "Meeresfrüchte",
    "menu.items.Odeng-Tang": "Odeng Tang",
    "menu.items.Odeng-TangDesc": "Warme Suppe mit Fischkuchen und Gemüse in einer klaren, herzhaften Brühe",
    "menu.items.Dolsot-Bibimbap": "Dolsot Bibimbap",
    "menu.items.Dolsot-BibimbapDesc": "Reis mit Rindfleisch und verschiedenen Gemüsesorten in einem heißen Steintopf",
    "menu.items.Dubu-Bibimbap": "Dubu Bibimbap",
    "menu.items.Dubu-BibimbapDesc": "Reis mit Tofu und verschiedenen Gemüsesorten in einem heißen Steintopf",
    "menu.items.Beosot-Bibimbap": "Beosot Bibimbap",
    "menu.items.Beosot-BibimbapDesc": "Reis mit Pilzen und verschiedenen Gemüsesorten in einem heißen Steintopf",
    "menu.items.Extra.Beef": "Extra Rindfleisch +2.0€",
    "menu.items.Extra.TofuMush": "Extra Tofu und Pilze +1.5€",
    "menu.items.Extra.Egg": "Extra Ei +1.0€",
    "menu.items.Gomtang": "Gomtang",
    "menu.items.GomtangDesc": "Kräftige Rinderbrühe mit weich gekochten, zarten Rindfleischscheiben und Glasnudeln",
    "menu.items.Yukgaejang": "Yukgaejang",
    "menu.items.YukgaejangDesc": "Würzige Suppe mit Rindfleisch und Gemüse",
    "menu.items.Ddeokbokki": "Ddeokbokki",
    "menu.items.DdeokbokkiDesc": "Scharf angebratener Reiskuchen mit Fischfrikadellen und Gemüse",
    "menu.items.Cheese-Ddeokbokki": "Cheese Ddeokbokki",
    "menu.items.Cheese-DdeokbokkiDesc": "Scharf angebratener Reiskuchen mitFischfrikadellen und Gemüse mit geschmolzenem Käse",
    "menu.items.Jjajang-Ddeokbokki": "Jjajang-Ddeokbokki",
    "menu.items.Jjajang-DdeokbokkiDesc": "Angebratener Reiskuchen mit schwarzer Bohnensauce, Rindfleisch, Fischfrikadellen und Gemüse",
    "menu.items.Gun-Mandu": "Gun-Mandu",
    "menu.items.Gun-ManduDesc": "Gebratene Maultaschen mit Gemüsefüllung",
    "menu.items.Kimchi-Jeon": "Kimchi-Jeon",
    "menu.items.Kimchi-JeonDesc": "Pikante Pfannkuchen mit gereiftem Kimchi",
    "menu.items.Pajeon": "Pajeon",
    "menu.items.PajeonDesc": "Pfannkuchen mit Lauchzwiebeln",
    "menu.items.pajeon.sub.seafood": "Meeresfrüchte",
    "menu.items.pajeon.sub.mushroom": "Pilze",
    "menu.items.Kimchi": "Kimchi",
    "menu.items.KimchiDesc": "Scharf eingelegter Chinakohl nach koreanischer Art",
    "menu.items.ExtraRice": "Extra Reis",
    "menu.items.ExtraFriedChickenSauce": "Extra Brathähnchensauce",
    "menu.items.ExtraFriedChickenSauceDesc": "Sauce für Brathähnchen (Yangnyeom / Ganjang)",
    "menu.items.ExtraColeslaw": "Extra Coleslaw",
    "menu.items.ExtraSauces": "Extra Saucen",
    "menu.items.ExtraSaucesDesc": "Saucen (Sojasauce, Chilipaste, Mayonnaise, Salatdressing)",
    "menu.items.ExtraCheese": "Extra Käse",
    "menu.items.ExtraPickledRadish": "Extra Eingelegter Rettich",
    "menu.items.ExtraSideDishes": "Extra Beilagen",


    "menu.findUs": "Finde uns",
    "menu.filters": "Filter",
    "menu.dietaryPreferences": "Ernährungsbedürfnisse",
    "menu.all": "Alle",
    "menu.vegetarian": "Vegetarisch",
    "menu.nonVegetarian": "Nicht vegetarisch",
    "menu.spicinessLevel": "Maximale Pfefferung",
    "menu.allLevels": "Alle Stufen",
    "menu.notSpicy": "Nicht pfefferig",
    "menu.mild": "Leicht",
    "menu.medium": "Mittel",
    "menu.hot": "Heiß",
    "menu.spiciness": "Pfefferung",
    "menu.allergens": "Allergene",
    "menu.chooseYourStyle": "Stil wählen",
  
    "menu.guide.title": "Bestellanleitung",
    "menu.guide.hover": "Erfahren Sie, wie Sie Hankki-Hähnchen bestellen",
    "menu.guide.step1.title": "1. Wählen Sie Ihren Stil",
    "menu.guide.step1.desc": "Wählen Sie zwischen unserem klassischen Hähnchen mit Knochen oder praktischen knochenlosen Stücken.",
    "menu.guide.step2.title": "2. Wählen Sie Ihre Größe",
    "menu.guide.step2.desc": "Wählen Sie M für ein halbes Hähnchen, perfekt für eine Person, oder L für ein ganzes Hähnchen, ideal zum Teilen.",
    "menu.guide.step3.title": "3. Wählen Sie Ihre Konfiguration",
    "menu.guide.step3.desc": "Entscheiden Sie sich für 'Whole', um einen Geschmack über Ihre gesamte Bestellung zu genießen, oder wählen Sie 'Half & Half', um zwei verschiedene Geschmacksrichtungen in einer Bestellung zu mischen und abzugleichen.",
    "menu.guide.step4.title": "4. Wählen Sie Ihre Geschmacksrichtung(en)",
    "menu.guide.step4.desc": "Wählen Sie aus unserer Auswahl an köstlichen Geschmacksrichtungen, von klassischem Soja-Knoblauch bis hin zu scharfem Gochujang. Wenn Sie 'Half & Half' ausgewählt haben, können Sie zwei verschiedene Geschmacksrichtungen auswählen, um das Beste aus beiden Welten zu genießen!",
    
    "menu.downloadPDF": "Als PDF herunterladen",
    "menu.downloadPDFAlert": "Menu PDF download would start here. In production, this would download the actual menu PDF.",
    
    "menu.openingHours": "Öffnungszeiten",
    "menu.mondayFriday": "Montag - Freitag",
    "menu.saturdaySunday": "Samstag - Sonntag",
    
    // Contact page
    "contact.title": "Kontakt",
    "contact.getInTouch": "Kontaktiere Uns",
    "contact.address": "Adresse",
    "contact.email": "E-Mail",
    "contact.phone": "Telefon",
    "contact.followUs": "Folge Uns",
    "contact.reservation": "Reservierung Vornehmen",
    "contact.name": "Vollständiger Name",
    "contact.phoneNumber": "Telefonnummer",
    "contact.emailAddress": "E-Mail-Adresse",
    "contact.numberOfGuests": "Anzahl der Gäste",
    "contact.dateTime": "Datum & Uhrzeit",
    "contact.date": "Datum",
    "contact.time": "Uhrzeit",
    "contact.mondayClosed": "Montag geschlossen",
    "contact.selectTime": "Uhrzeit auswählen",
    "contact.submit": "Reservierungsanfrage Absenden",
    "contact.submitAlert": "Ihre Reservierungsanfrage wurde erhalten. Wir werden die Verfügbarkeit prüfen und uns so schnell wie möglich bei Ihnen melden.",
    "contact.required": "* Alle Felder sind erforderlich",
    "contact.alert":"⚠️ Online-Reservierungen für den gleichen Tag sind nicht möglich!",
    "contact.selectGuests": "Gäste wählen",
    "contact.guest": "Gast",
    "contact.guestsPlural": "Gäste",
    "contact.namePlaceholder": "Geben Sie Ihren Namen ein",
    "contact.phonePlaceholder": "+62 xxx xxxx xxxx",
    "contact.emailPlaceholder": "ihre.email@beispiel.com",
    
    // Footer
    "footer.tagline": "Kommen Sie und probieren Sie unser Unternehmen hier aus",
    
    // Days
    "days.tuesday": "Dienstag",
    "days.friday": "Freitag",
    "days.saturday": "Samstag",
    "days.sunday": "Sonntag",
    "days.monday": "Montag",
  },
  kr: {
    // Navigation
    "nav.about": "소개",
    "nav.menu": "메뉴",
    "nav.contact": "연락처",
    
    // Home page
    "home.aboutUs": "우리에 대해",
    "home.aboutText": "특색 있는 테이크아웃 공간과 장식된 여관에서 \"Hankki\"는 500가지 이상의 종류와 자연스러운 관계 테이크아웃을 제공합니다. 자카르타 최고의 한국 치킨을 제공하는 것을 자랑스럽게 생각합니다.",
    "home.menu": "메뉴",
    "home.chicken": "치킨",
    "home.chickenDesc": "특색 있는 테이크아웃 공간에는 여러 종류가 있습니다. 맛있는 치킨을 먹으러 왔습니다. 치킨의 다양한 종류나 스타일을 설명하는 텍스트입니다.",
    "home.goToMenu": "메뉴로 이동 →",
    "home.openingHours": "영업 간",
    "home.weekday": "평일",
    "home.closed": "휴무",
    "home.contact": "연락처",
    "home.makeReservation": "예약하기 →",
    "home.hero.title": "HANKKI",
    "home.hero.subtitle": "Korean Fried Chicken",
    "home.hero.description": "Experience authentic Korean flavors in the heart of Cologne",
    "home.menu.item1.name": "Original Fried Chicken",
    "home.menu.item1.desc": "Crispy golden fried chicken with our signature Korean spices. Perfectly seasoned and fried to perfection.",
    "home.menu.item2.name": "Spicy Korean Wings",
    "home.menu.item2.desc": "Succulent chicken wings glazed with our house special gochujang sauce. A fan favorite!",
    "home.menu.item3.name": "Honey Garlic Chicken",
    "home.menu.item3.desc": "Sweet and savory chicken pieces coated in our signature honey garlic glaze.",
    "home.kitchenUntil": "Kitchen until",
    
    // About page
    "about.title": "소개",
    "about.ourStory": "우리의 이야기",
    "about.storyText": "특색 있는 테이크아웃 공간과 장식된 여관에서 \"Hankki\"는 500가지 이상의 종류와 자연스러운 관계를 제공합니다. 자카르타 최고의 한국 치킨을 제공하는 것을 자랑스럽게 생각합니다. 우리의 레시피는 수년에 걸쳐 완성되었으며 전통적인 한국 요리 기법과 현지 재료를 결합합니다.",
    "about.ourValues": "우리의 가치",
    "about.value1Title": "품질",
    "about.value1Text": "우리는 최고의 재료만 사용하고 제공하는 모든 요리에서 최고 기준을 유지합니다.",
    "about.value2Title": "열정",
    "about.value2Text": "한국 요리에 대한 우리의 사랑은 모든 레시피를 완벽하게 만들도록 합니다.",
    "about.value3Title": "커뮤니티",
    "about.value3Text": "고객과의 지속적인 관계를 구축하고 지역 사회의 일부가 되는 것을 믿습니다.",
    "about.hansikTitle": "한국 전통 요리",
    "about.hansikText": "한식은 한국의 전통 음식 문화를 나타내며 균형 잡힌 영양과 조화를 강조합니다. 우리의 요리는 이 수세기 된 요리 전통에서 영감을 받아 자카르타에 정통 한국 맛을 선사합니다.",
    "about.teamTitle": "우리 팀",
    "about.teamText": "우리 팀은 고객에게 최고의 한국 요리를 제공하기 위해 헌신하는 열정적인 음식 애호가 그룹입니다. 각 요리를 정성스럽게 준비하는 재능 있는 셰프부터 친절한 직원까지, 우리는 우리가 하는 모든 일에서 탁월함을 위해 노력합니다. Hankki의 사람들을 만나고 맛있는 한국 치킨과 더 많은 것을 제공하기 위해 우리를 움직이는 열정을 발견하십시오.",
    // Menu page
    "menu.title": "메뉴",
    "menu.categories.stew": "찌개",
    "menu.categories.soup": "국물",
    "menu.categories.bulgogi": "불고기",  
    "menu.categories.all": "전체",
    "menu.categories.friedChicken": "한끼 치킨",
    "menu.categories.chicken": "치킨",
    "menu.categories.pancake": "전",
    "menu.categories.noodle": "면",
    "menu.categories.bibimbap": "비빔밥",
    "menu.categories.streetfood": "길거리 음식",
    "menu.categories.side": "사이드", 
    "menu.categories.drinks": "음료",
    "menu.categories.extra": "추가 옵션",
    "menu.extra": "추가 옵션",
    "menu.included": "포함된 항목",


    // Menu items
    "menu.items.budaeJjigae": "부대찌개",
    "menu.items.budaeJjigaeDesc": "소시지, 돼지고기, 라면과 야채가 들어간 매운 찌개",
    "menu.items.budaeJjigae.included": "밥 2그릇 포함",
    "menu.items.budaeJjigae.extra": "라면사리 추가 +2€",
    "menu.items.bulgogijeongol": "불고기전골",
    "menu.items.bulgogijeongolDesc": "간장 육수에 야채와 버섯이 들어간 고소한 소고기 전골",
    "menu.items.bulgogijeongol.included": "밥 2그릇 포함",
    "menu.items.dakgalbi": "닭갈비",
    "menu.items.dakgalbiDesc": "야채와 떡이 들어간 매운 볶음 닭",
    "menu.items.dakgalbi.included": "밥 2그릇 포함",
    "menu.items.dakgalbi.extra": "치즈 추가 +3€",
    "menu.items.gochujangBulgogi": "고추장 불고기",
    "menu.items.gochujangBulgogiDesc": "매운 양념에 볶은 돼지고기",
    "menu.items.ganjangDoejiBulgogi": "간장 돼지 불고기",
    "menu.items.ganjangDoejiBulgogiDesc": "진한 간장 양념에 볶은 돼지고기",
    "menu.items.Bulgogi": "소불고기",
    "menu.items.BulgogiDesc": "간장 양념에 볶은 소고기",
    "menu.items.cheeseBuldak": "치즈 불닭",
    "menu.items.cheeseBuldakDesc": "매운 양념에 볶은 치킨과 치즈",
    "menu.items.jjimDak": "찜닭",
    "menu.items.jjimDakDesc": "간장 양념에 찐 닭",
    "menu.items.japchae": "잡채",
    "menu.items.japchaeDesc": "야채와 볶은 당면",
    "menu.items.japchae.sub.beef": "소고기",
    "menu.items.japchae.sub.mushroom": "버섯",
    "menu.items.kimchiJjigae.sub.porkTofu": "돼지고기와 두부",
    "menu.items.kimchiJjigae.sub.porkOnly": "돼지고기만",
    "menu.items.kimchiJjigae.sub.tofuOnly": "두부만",
    "menu.items.kimchiJjigae": "김치찌개",
    "menu.items.kimchiJjigaeDesc": "김치로 만든 매운 찌개",
    "menu.items.Doenjang-Jjigae": "된장찌개",
    "menu.items.Doenjang-JjigaeDesc": "된장, 두부, 야채가 들어간 찌개",
    "menu.items.Doenjang-Jjigae.sub.Vegetables": "야채",
    "menu.items.Doenjang-Jjigae.sub.Seafood": "해산물",
    "menu.items.Odeng-Tang": "오뎅탕",
    "menu.items.Odeng-TangDesc": "맑고 고소한 국물에 어묵과 야채가 들어간 따뜻한 국물",
    "menu.items.Dolsot-Bibimbap": "돌솥 비빔밥",
    "menu.items.Dolsot-BibimbapDesc": "뜨거운 돌솥에 소고기와 다양한 야채가 들어간 밥",
    "menu.items.Dubu-Bibimbap": "두부 비빔밥",
    "menu.items.Dubu-BibimbapDesc": "뜨거운 돌솥에 두부와 다양한 야채가 들어간 밥",
    "menu.items.Beosot-Bibimbap": "버섯 비빔밥",
    "menu.items.Beosot-BibimbapDesc": "뜨거운 돌솥에 버섯과 다양한 야채가 들어간 밥",
    "menu.items.Extra.Beef": "소고기 추가 +2.0€",
    "menu.items.Extra.TofuMush": "두부와 버섯 추가 +1.5€",
    "menu.items.Extra.Egg": "계란 추가 +1.0€",
    "menu.items.Gomtang": "곰탕",
    "menu.items.GomtangDesc": "부드럽고 연한 삶은 소고기 조각과 당면이 들어간 소고기 육수",
    "menu.items.Yukgaejang": "육개장",
    "menu.items.YukgaejangDesc": "소고기와 야채가 들어간 매운 찌개",
    "menu.items.Ddeokbokki": "떡볶이",
    "menu.items.DdeokbokkiDesc": "어묵과 야채가 들어간 매운 볶음 떡",
    "menu.items.Cheese-Ddeokbokki": "치즈 떡볶이",
    "menu.items.Cheese-DdeokbokkiDesc": "어묵과 야채가 들어간 매운 볶음 떡에 녹인 치즈",
    "menu.items.Jjajang-Ddeokbokki": "짜장 떡볶이",
    "menu.items.Jjajang-DdeokbokkiDesc": "검은 콩 소스, 소고기, 어묵, 야채가 들어간 볶음 떡",
    "menu.items.Gun-Mandu": "군만두",
    "menu.items.Gun-ManduDesc": "야채로 속을 채운 군만두",
    "menu.items.Kimchi-Jeon": "김치전",
    "menu.items.Kimchi-JeonDesc": "숙성된 김치로 만든 매운 전",
    "menu.items.Pajeon": "파전",
    "menu.items.PajeonDesc": "파가 들어간 전",
    "menu.items.Pajeon.sub.seafood": "해산물",
    "menu.items.Pajeon.sub.mushroom": "버섯",
    "menu.items.Kimchi": "김치",
    "menu.items.KimchiDesc": "한국식 매운 양념으로 절인 배추",
    "menu.items.ExtraRice": "밥 추가",
    "menu.items.ExtraFriedChickenSauce": "브라운 치킨 소스 추가",
    "menu.items.ExtraFriedChickenSauceDesc": "브라운 치킨용 소스 (양념 / 간장)",
    "menu.items.ExtraColeslaw": "콜슬로 추가",
    "menu.items.ExtraSauces": "소스 추가",
    "menu.items.ExtraSaucesDesc": "소스 (간장, 고추장, 마요네즈, 샐러드 드레싱)",
    "menu.items.ExtraCheese": "치즈 추가",
    "menu.items.ExtraPickledRadish": "절인 무 추가",
    "menu.items.ExtraSideDishes": "사이드 추가",

    "menu.findUs": "찾아오시는 길",
    "menu.filters": "필터",
    "menu.dietaryPreferences": "식단 선호도",
    "menu.all": "전체",
    "menu.vegetarian": "채식주의",
    "menu.nonVegetarian": "비채식주의",
    "menu.spicinessLevel": "최대 매운 정도",
    "menu.allLevels": "모든 수준",
    "menu.notSpicy": "매운게 아님",
    "menu.mild": "약간 매운",
    "menu.medium": "중간 매운",
    "menu.hot": "매운",
    "menu.spiciness": "매운 정도",
    "menu.allergens": "알레르기 유발물질",

    "menu.guide.title": "주문 가이드",
    "menu.guide.hover": "한끼 치킨 주문 방법 알아보기",
    "menu.guide.step1.title": "1. 스타일 선택",
    "menu.guide.step1.desc": "뼈 있는 치킨 또는 순살 중 선택하세요.",
    "menu.guide.step2.title": "2. 사이즈 선택",
    "menu.guide.step2.desc": "M(반 마리) 또는 L(한 마리) 중 선택하세요.",
    "menu.guide.step3.title": "3. 구성 선택",
    "menu.guide.step3.desc": "한 가지 맛인 'Whole' 또는 두 가지 맛을 고를 수 있는 'Half & Half' 중 선택하세요.",
    "menu.guide.step4.title": "4. 소스 선택",
    "menu.guide.step4.desc": "오리지널, 양념, 간장을 취향대로! 'Half & Half'를 고르셨다면 소스 2가지를 선택할 수 있습니다.",

    "menu.downloadPDF": "PDF 다운로드",
    "menu.downloadPDFAlert": "Menu PDF download would start here. In production, this would download the actual menu PDF.",

    "menu.openingHours": "영업 시간",
    "menu.mondayFriday": "월요일 - 금요일",
    "menu.saturdaySunday": "토요일 - 일요일",
    
    // Contact page
    "contact.title": "연락처",
    "contact.getInTouch": "연락하기",
    "contact.address": "주소",
    "contact.email": "이메일",
    "contact.phone": "전화",
    "contact.followUs": "팔로우",
    "contact.reservation": "예약 요청",
    "contact.name": "이름",
    "contact.phoneNumber": "전화번호",
    "contact.emailAddress": "이메일 주소",
    "contact.numberOfGuests": "인원 수",
    "contact.dateTime": "날짜 & 시간",
    "contact.date": "날짜",
    "contact.time": "시간",
    "contact.mondayClosed": "월요일 휴무",
    "contact.selectTime": "시간 선택",
    "contact.submit": "예약 요청 제출",
    "contact.submitAlert": "예약 요청이 접수되었습니다. 예약 가능 여부를 확인한 후 최대한 빨리 연락드리겠습니다.",
    "contact.required": "* 모든 필드는 필수입니다",
    "contact.alert":"⚠️ 당일 예약은 온라인으로 불가능합니다!",
    "contact.selectGuests": "인원 선택",
    "contact.guest": "명",
    "contact.guestsPlural": "명",
    "contact.namePlaceholder": "이름을 입력하세요",
    "contact.phonePlaceholder": "+62 xxx xxxx xxxx",
    "contact.emailPlaceholder": "your.email@example.com",
    
    // Footer
    "footer.tagline": "여기에서 우리 회사에 대해 시도해보십시오",
    
    // Days
    "days.tuesday": "화요일",
    "days.friday": "금요일",
    "days.saturday": "토요일",
    "days.sunday": "일요일",
    "days.monday": "월요일",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("en");

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.en] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}