import { createContext, useContext, useState, ReactNode } from "react";

type Language = "en" | "de" | "kr";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Navigation
    "nav.about": "ABOUT",
    "nav.menu": "MENU",
    "nav.contact": "CONTACT",
    
    // Home page
    "home.aboutUs": "About us",
    "home.aboutText": "In our characteristic takeaway space and decorated inn, \"Hankki\" ultra indulges the fans, which carries 500 types and natural relationship takeaway upon one line line. We pride ourselves on serving the finest Korean fried chicken in Jakarta.",
    "home.menu": "Menu",
    "home.chicken": "Chicken",
    "home.chickenDesc": "In our characteristic takeaway space and decorated inn, there are more than couple. We are here to eat delicious fried chicken. Some text describing the chicken which has great variety or style can fill in be be.",
    "home.goToMenu": "Go to menu →",
    "home.openingHours": "Opening Hours",
    "home.weekday": "Weekday",
    "home.closed": "Closed",
    "home.contact": "Contact",
    "home.makeReservation": "Make a reservation →",
    "home.hero.title": "HANKKI",
    "home.hero.subtitle": "Korean Fried Chicken",
    "home.hero.description": "Experience authentic Korean flavors in the heart of Cologne",
    "home.menu.item1.name": "Original Fried Chicken",
    "home.menu.item1.desc": "Crispy golden fried chicken with our signature Korean spices. Perfectly seasoned and fried to perfection.",
    "home.menu.item2.name": "Spicy Korean Wings",
    "home.menu.item2.desc": "Succulent chicken wings glazed with our house special gochujang sauce. A fan favorite!",
    "home.menu.item3.name": "Honey Garlic Chicken",
    "home.menu.item3.desc": "Sweet and savory chicken pieces coated in our signature honey garlic glaze.",
    "home.kitchenUntil": "Kitchen until",
    
    // About page
    "about.title": "About Us",
    "about.ourStory": "Our Story",
    "about.storyText": "In our characteristic takeaway space and decorated inn, \"Hankki\" ultra indulges the fans, which carries 500 types and natural relationship takeaway upon one line line. We pride ourselves on serving the finest Korean fried chicken in Cologne. Our recipes have been perfected over years, combining traditional Korean cooking techniques with locally sourced ingredients to create a unique dining experience.",
    "about.ourValues": "Our Values",
    "about.value1Title": "Quality",
    "about.value1Text": "We use only the finest ingredients and maintain the highest standards in every dish we serve.",
    "about.value2Title": "Passion",
    "about.value2Text": "Our love for Korean cuisine drives us to perfect every recipe and create memorable dining experiences.",
    "about.value3Title": "Community",
    "about.value3Text": "We believe in building lasting relationships with our customers and being part of the local community.",
    "about.hansikTitle": "Korean Traditional Cuisine",
    "about.hansikText": "Hansik represents the traditional food culture of Korea, emphasizing balanced nutrition and harmony. Our dishes are inspired by this centuries-old culinary tradition, bringing authentic Korean flavors to Cologne. From our signature fried chicken to traditional side dishes, every element is crafted with respect for Korean culinary heritage.",
    
    // Menu page
    "menu.title": "Menu",
    "menu.categories.all": "All",
    "menu.categories.friedChicken": "Fried Chicken",
    "menu.categories.soups": "Soups",
    "menu.categories.snacksSides": "Snacks & Sides",
    "menu.categories.drinks": "Drinks",
    "menu.items.original": "Original",
    "menu.items.yangnyeom": "Yangnyeom",
    "menu.items.ganjang": "Ganjang",
    "menu.items.kimchiJjigae": "Kimchi Jjigae",
    "menu.items.koreanFries": "Korean Fries",
    "menu.items.soju": "Soju",
    "menu.findUs": "Find us",
    "menu.filters": "Filters",
    "menu.dietaryPreferences": "Dietary Preferences",
    "menu.all": "All",
    "menu.vegetarian": "Vegetarian",
    "menu.nonVegetarian": "Non-Vegetarian",
    "menu.spicinessLevel": "Maximum Spiciness Level",
    "menu.allLevels": "All Levels",
    "menu.notSpicy": "Not Spicy",
    "menu.mild": "Mild",
    "menu.medium": "Medium",
    "menu.hot": "Hot",
    "menu.spiciness": "Spiciness",
    "menu.allergens": "Allergens",
    "menu.chooseYourStyle": "Choose Your Style",
    "menu.withBones": "With Bones",
    "menu.withBonesDesc": "Traditional style with juicy meat on the bone. More flavorful and authentic.",
    "menu.withoutBones": "Without Bones",
    "menu.withoutBonesDesc": "Boneless pieces for easy eating. Perfect for sharing and snacking.",
    "menu.selectYourPortion": "Select Your Portion",
    "menu.whole": "Whole",
    "menu.wholeDesc": "Choose one flavor for your entire order.",
    "menu.halfAndHalf": "Half & Half",
    "menu.halfAndHalfDesc": "Mix two different flavors in one order.",
    "menu.pickYourFlavor": "Pick Your Flavor",
    "menu.pickYourFlavors": "Pick Your Flavors",
    "menu.downloadPDF": "Download Menu PDF",
    "menu.downloadPDFAlert": "Menu PDF download would start here. In production, this would download the actual menu PDF.",
    "menu.friedChickenNote": "All fried chicken available with or without bones. Please specify your preference when ordering.",
    "menu.selectYourSize": "Select Your Size",
    "menu.sizeM": "Half Chicken",
    "menu.sizeMDesc": "Half chicken - perfect for one person. Choose one flavor.",
    "menu.sizeL": "Whole Chicken",
    "menu.sizeLDesc": "Whole chicken - great for sharing. Choose one flavor or mix two!",
    "menu.items.doenjangJjigae": "Doenjang Jjigae",
    "menu.items.sundubuJjigae": "Sundubu Jjigae",
    "menu.items.yukgaejang": "Yukgaejang",
    "menu.items.samgyetang": "Samgyetang",
    "menu.items.galbitang": "Galbitang",
    "menu.items.tteokbokki": "Tteokbokki",
    "menu.items.mandu": "Mandu",
    "menu.items.edamame": "Edamame",
    "menu.items.makgeolli": "Makgeolli",
    "menu.items.plumTea": "Korean Plum Tea",
    "menu.items.yuzuSoda": "Yuzu Soda",
    "menu.openingHours": "Opening Hours",
    "menu.mondayFriday": "Monday - Friday",
    "menu.saturdaySunday": "Saturday - Sunday",
    
    // Contact page
    "contact.title": "Contact",
    "contact.getInTouch": "Get in Touch",
    "contact.address": "Address",
    "contact.email": "Email",
    "contact.phone": "Phone",
    "contact.followUs": "Follow Us",
    "contact.reservation": "Reservation Request",
    "contact.name": "Full Name",
    "contact.phoneNumber": "Phone Number",
    "contact.emailAddress": "Email Address",
    "contact.numberOfGuests": "Number of Guests",
    "contact.dateTime": "Date & Time",
    "contact.date": "Date",
    "contact.time": "Time",
    "contact.mondayClosed": "Monday closed",
    "contact.selectTime": "Select time",
    "contact.submit": "Submit Request",
    "contact.submitAlert": "Your reservation request has been received. We will check availability and get back to you as soon as possible.",
    "contact.required": "* All fields are required",
    "contact.alert":"⚠️ Same-day reservations are not possible online!",
    "contact.selectGuests": "Select guests",
    "contact.guest": "Guest",
    "contact.guestsPlural": "Guests",
    "contact.namePlaceholder": "Enter your name",
    "contact.phonePlaceholder": "+62 xxx xxxx xxxx",
    "contact.emailPlaceholder": "your.email@example.com",
    
    // Footer
    "footer.tagline": "Come try our about your company here",
    
    // Days
    "days.tuesday": "Tuesday",
    "days.friday": "Friday",
    "days.saturday": "Saturday",
    "days.sunday": "Sunday",
    "days.monday": "Monday",
  },
  de: {
    // Navigation
    "nav.about": "ÜBER UNS",
    "nav.menu": "SPEISEKARTE",
    "nav.contact": "KONTAKT",
    
    // Home page
    "home.aboutUs": "Über uns",
    "home.aboutText": "In unserem charakteristischen Takeaway-Raum und dekorierten Gasthaus verwöhnt \"Hankki\" die Fans mit über 500 Sorten. Wir sind stolz darauf, das beste koreanische Brathähnchen in Jakarta zu servieren.",
    "home.menu": "Speisekarte",
    "home.chicken": "Hähnchen",
    "home.chickenDesc": "In unserem charakteristischen Takeaway-Raum gibt es mehr als ein paar. Wir sind hier, um köstliches Brathähnchen zu essen. Ein Text, der das Hähnchen beschreibt, das eine große Vielfalt oder einen großen Stil hat.",
    "home.goToMenu": "Zur Speisekarte →",
    "home.openingHours": "Öffnungszeiten",
    "home.weekday": "Wochentag",
    "home.closed": "Geschlossen",
    "home.contact": "Kontakt",
    "home.makeReservation": "Reservierung vornehmen →",
    "home.hero.title": "HANKKI",
    "home.hero.subtitle": "Korean Fried Chicken",
    "home.hero.description": "Experience authentic Korean flavors in the heart of Cologne",
    "home.menu.item1.name": "Original Fried Chicken",
    "home.menu.item1.desc": "Crispy golden fried chicken with our signature Korean spices. Perfectly seasoned and fried to perfection.",
    "home.menu.item2.name": "Spicy Korean Wings",
    "home.menu.item2.desc": "Succulent chicken wings glazed with our house special gochujang sauce. A fan favorite!",
    "home.menu.item3.name": "Honey Garlic Chicken",
    "home.menu.item3.desc": "Sweet and savory chicken pieces coated in our signature honey garlic glaze.",
    "home.kitchenUntil": "Kitchen until",
    
    // About page
    "about.title": "Über Uns",
    "about.ourStory": "Unsere Geschichte",
    "about.storyText": "In unserem charakteristischen Takeaway-Raum und dekorierten Gasthaus verwöhnt \"Hankki\" die Fans mit über 500 Sorten und natürlicher Beziehung. Wir sind stolz darauf, das beste koreanische Brathähnchen in Köln zu servieren. Unsere Rezepte wurden über Jahre perfektioniert und kombinieren traditionelle koreanische Kochtechniken mit lokalen Zutaten.",
    "about.ourValues": "Unsere Werte",
    "about.value1Title": "Qualität",
    "about.value1Text": "Wir verwenden nur die besten Zutaten und halten die höchsten Standards in jedem Gericht ein.",
    "about.value2Title": "Leidenschaft",
    "about.value2Text": "Unsere Liebe zur koreanischen Küche treibt uns an, jedes Rezept zu perfektionieren.",
    "about.value3Title": "Gemeinschaft",
    "about.value3Text": "Wir glauben daran, dauerhafte Beziehungen zu unseren Kunden aufzubauen.",
    "about.hansikTitle": "Traditionelle Koreanische Küche",
    "about.hansikText": "Hansik repräsentiert die traditionelle Esskultur Koreas und betont ausgewogene Ernährung und Harmonie. Unsere Gerichte sind von dieser jahrhundertealten kulinarischen Tradition inspiriert und bringen authentische koreanische Aromen nach Köln.",
    
    // Menu page
    "menu.title": "Speisekarte",
    "menu.categories.all": "Alle",
    "menu.categories.friedChicken": "Brathähnchen",
    "menu.categories.soups": "Suppen",
    "menu.categories.snacksSides": "Snacks & Beilagen",
    "menu.categories.drinks": "Getränke",
    "menu.items.original": "Original",
    "menu.items.yangnyeom": "Yangnyeom",
    "menu.items.ganjang": "Ganjang",
    "menu.items.kimchiJjigae": "Kimchi Jjigae",
    "menu.items.koreanFries": "Koreanische Pommes",
    "menu.items.soju": "Soju",
    "menu.findUs": "Finde uns",
    "menu.filters": "Filter",
    "menu.dietaryPreferences": "Ernährungsbedürfnisse",
    "menu.all": "Alle",
    "menu.vegetarian": "Vegetarisch",
    "menu.nonVegetarian": "Nicht vegetarisch",
    "menu.spicinessLevel": "Maximale Pfefferung",
    "menu.allLevels": "Alle Stufen",
    "menu.notSpicy": "Nicht pfefferig",
    "menu.mild": "Leicht",
    "menu.medium": "Mittel",
    "menu.hot": "Heiß",
    "menu.spiciness": "Pfefferung",
    "menu.allergens": "Allergene",
    "menu.chooseYourStyle": "Stil wählen",
    "menu.withBones": "Mit Knochen",
    "menu.withBonesDesc": "Traditioneller Stil mit saftigem Fleisch auf den Knochen. Geschmackvoller und authentischer.",
    "menu.withoutBones": "Ohne Knochen",
    "menu.withoutBonesDesc": "Knochlose Stücke für einfaches Essen. Perfekt zum Teilen und Snacken.",
    "menu.selectYourPortion": "Portion wählen",
    "menu.whole": "Ganze",
    "menu.wholeDesc": "Wählen Sie einen Geschmack für Ihre gesamte Bestellung.",
    "menu.halfAndHalf": "Halb & Halb",
    "menu.halfAndHalfDesc": "Mischen Sie zwei verschiedene Geschmacksrichtungen in einer Bestellung.",
    "menu.pickYourFlavor": "Geschmack wählen",
    "menu.pickYourFlavors": "Geschmacksrichtungen wählen",
    "menu.downloadPDF": "Speisekarte als PDF herunterladen",
    "menu.downloadPDFAlert": "Menu PDF download would start here. In production, this would download the actual menu PDF.",
    "menu.friedChickenNote": "All fried chicken available with or without bones. Please specify your preference when ordering.",
    "menu.selectYourSize": "Select Your Size",
    "menu.sizeM": "Half Chicken",
    "menu.sizeMDesc": "Half chicken - perfect for one person. Choose one flavor.",
    "menu.sizeL": "Whole Chicken",
    "menu.sizeLDesc": "Whole chicken - great for sharing. Choose one flavor or mix two!",
    "menu.items.doenjangJjigae": "Doenjang Jjigae",
    "menu.items.sundubuJjigae": "Sundubu Jjigae",
    "menu.items.yukgaejang": "Yukgaejang",
    "menu.items.samgyetang": "Samgyetang",
    "menu.items.galbitang": "Galbitang",
    "menu.items.tteokbokki": "Tteokbokki",
    "menu.items.mandu": "Mandu",
    "menu.items.edamame": "Edamame",
    "menu.items.makgeolli": "Makgeolli",
    "menu.items.plumTea": "Korean Plum Tea",
    "menu.items.yuzuSoda": "Yuzu Soda",
    "menu.openingHours": "Öffnungszeiten",
    "menu.mondayFriday": "Montag - Freitag",
    "menu.saturdaySunday": "Samstag - Sonntag",
    
    // Contact page
    "contact.title": "Kontakt",
    "contact.getInTouch": "Kontaktiere Uns",
    "contact.address": "Adresse",
    "contact.email": "E-Mail",
    "contact.phone": "Telefon",
    "contact.followUs": "Folge Uns",
    "contact.reservation": "Reservierung Vornehmen",
    "contact.name": "Vollständiger Name",
    "contact.phoneNumber": "Telefonnummer",
    "contact.emailAddress": "E-Mail-Adresse",
    "contact.numberOfGuests": "Anzahl der Gäste",
    "contact.dateTime": "Datum & Uhrzeit",
    "contact.date": "Datum",
    "contact.time": "Uhrzeit",
    "contact.mondayClosed": "Montag geschlossen",
    "contact.selectTime": "Uhrzeit auswählen",
    "contact.submit": "Reservierung Absenden",
    "contact.submitAlert": "Ihre Reservierungsanfrage wurde erhalten. Wir werden die Verfügbarkeit prüfen und uns so schnell wie möglich bei Ihnen melden.",
    "contact.required": "* Alle Felder sind erforderlich",
    "contact.alert":"⚠️ Online-Reservierungen für den gleichen Tag sind nicht möglich!",
    "contact.selectGuests": "Gäste wählen",
    "contact.guest": "Gast",
    "contact.guestsPlural": "Gäste",
    "contact.namePlaceholder": "Geben Sie Ihren Namen ein",
    "contact.phonePlaceholder": "+62 xxx xxxx xxxx",
    "contact.emailPlaceholder": "ihre.email@beispiel.com",
    
    // Footer
    "footer.tagline": "Kommen Sie und probieren Sie unser Unternehmen hier aus",
    
    // Days
    "days.tuesday": "Dienstag",
    "days.friday": "Freitag",
    "days.saturday": "Samstag",
    "days.sunday": "Sonntag",
    "days.monday": "Montag",
  },
  kr: {
    // Navigation
    "nav.about": "소개",
    "nav.menu": "메뉴",
    "nav.contact": "연락처",
    
    // Home page
    "home.aboutUs": "우리에 대해",
    "home.aboutText": "특색 있는 테이크아웃 공간과 장식된 여관에서 \"Hankki\"는 500가지 이상의 종류와 자연스러운 관계 테이크아웃을 제공합니다. 자카르타 최고의 한국 치킨을 제공하는 것을 자랑스럽게 생각합니다.",
    "home.menu": "메뉴",
    "home.chicken": "치킨",
    "home.chickenDesc": "특색 있는 테이크아웃 공간에는 여러 종류가 있습니다. 맛있는 치킨을 먹으러 왔습니다. 치킨의 다양한 종류나 스타일을 설명하는 텍스트입니다.",
    "home.goToMenu": "메뉴로 이동 →",
    "home.openingHours": "영업 간",
    "home.weekday": "평일",
    "home.closed": "휴무",
    "home.contact": "연락처",
    "home.makeReservation": "예약하기 →",
    "home.hero.title": "HANKKI",
    "home.hero.subtitle": "Korean Fried Chicken",
    "home.hero.description": "Experience authentic Korean flavors in the heart of Cologne",
    "home.menu.item1.name": "Original Fried Chicken",
    "home.menu.item1.desc": "Crispy golden fried chicken with our signature Korean spices. Perfectly seasoned and fried to perfection.",
    "home.menu.item2.name": "Spicy Korean Wings",
    "home.menu.item2.desc": "Succulent chicken wings glazed with our house special gochujang sauce. A fan favorite!",
    "home.menu.item3.name": "Honey Garlic Chicken",
    "home.menu.item3.desc": "Sweet and savory chicken pieces coated in our signature honey garlic glaze.",
    "home.kitchenUntil": "Kitchen until",
    
    // About page
    "about.title": "소개",
    "about.ourStory": "우리의 이야기",
    "about.storyText": "특색 있는 테이크아웃 공간과 장식된 여관에서 \"Hankki\"는 500가지 이상의 종류와 자연스러운 관계를 제공합니다. 자카르타 최고의 한국 치킨을 제공하는 것을 자랑스럽게 생각합니다. 우리의 레시피는 수년에 걸쳐 완성되었으며 전통적인 한국 요리 기법과 현지 재료를 결합합니다.",
    "about.ourValues": "우리의 가치",
    "about.value1Title": "품질",
    "about.value1Text": "우리는 최고의 재료만 사용하고 제공하는 모든 요리에서 최고 기준을 유지합니다.",
    "about.value2Title": "열정",
    "about.value2Text": "한국 요리에 대한 우리의 사랑은 모든 레시피를 완벽하게 만들도록 합니다.",
    "about.value3Title": "커뮤니티",
    "about.value3Text": "고객과의 지속적인 관계를 구축하고 지역 사회의 일부가 되는 것을 믿습니다.",
    "about.hansikTitle": "한국 전통 요리",
    "about.hansikText": "한식은 한국의 전통 음식 문화를 나타내며 균형 잡힌 영양과 조화를 강조합니다. 우리의 요리는 이 수세기 된 요리 전통에서 영감을 받아 자카르타에 정통 한국 맛을 선사합니다.",
    
    // Menu page
    "menu.title": "메뉴",
    "menu.categories.all": "전체",
    "menu.categories.friedChicken": "후라이드 치킨",
    "menu.categories.soups": "국물",
    "menu.categories.snacksSides": "스낵 & 사이드",
    "menu.categories.drinks": "음료",
    "menu.items.original": "오리지널",
    "menu.items.yangnyeom": "양냐음",
    "menu.items.ganjang": "간장",
    "menu.items.kimchiJjigae": "김치찌개",
    "menu.items.koreanFries": "한국 감자 튀김",
    "menu.items.soju": "소주",
    "menu.findUs": "찾아오시는 길",
    "menu.filters": "필터",
    "menu.dietaryPreferences": "식단 선호도",
    "menu.all": "전체",
    "menu.vegetarian": "채식주의",
    "menu.nonVegetarian": "비채식주의",
    "menu.spicinessLevel": "최대 매운 정도",
    "menu.allLevels": "모든 수준",
    "menu.notSpicy": "매운게 아님",
    "menu.mild": "약간 매운",
    "menu.medium": "중간 매운",
    "menu.hot": "매운",
    "menu.spiciness": "매운 정도",
    "menu.allergens": "알레르기 유발물질",
    "menu.chooseYourStyle": "스타일 선택",
    "menu.withBones": "뼈가 있는",
    "menu.withBonesDesc": "뼈 위에 달달한 고기로 전통적인 스타일. 더 맛있고 진정한 맛.",
    "menu.withoutBones": "뼈가 없는",
    "menu.withoutBonesDesc": "뼈 없는 조각으로 쉽게 먹을 수 있습니다. 공유하고 간식으로 즐기기 좋습니다.",
    "menu.selectYourPortion": "포션 선택",
    "menu.whole": "전체",
    "menu.wholeDesc": "주문 전체에 하나의 맛을 선택합니다.",
    "menu.halfAndHalf": "반반",
    "menu.halfAndHalfDesc": "하나의 주문에 두 가지 다른 맛을 섞습니다.",
    "menu.pickYourFlavor": "맛 선택",
    "menu.pickYourFlavors": "맛들 선택",
    "menu.downloadPDF": "메뉴 PDF 다운로드",
    "menu.downloadPDFAlert": "Menu PDF download would start here. In production, this would download the actual menu PDF.",
    "menu.friedChickenNote": "All fried chicken available with or without bones. Please specify your preference when ordering.",
    "menu.selectYourSize": "Select Your Size",
    "menu.sizeM": "Half Chicken",
    "menu.sizeMDesc": "Half chicken - perfect for one person. Choose one flavor.",
    "menu.sizeL": "Whole Chicken",
    "menu.sizeLDesc": "Whole chicken - great for sharing. Choose one flavor or mix two!",
    "menu.items.doenjangJjigae": "Doenjang Jjigae",
    "menu.items.sundubuJjigae": "Sundubu Jjigae",
    "menu.items.yukgaejang": "Yukgaejang",
    "menu.items.samgyetang": "Samgyetang",
    "menu.items.galbitang": "Galbitang",
    "menu.items.tteokbokki": "Tteokbokki",
    "menu.items.mandu": "Mandu",
    "menu.items.edamame": "Edamame",
    "menu.items.makgeolli": "Makgeolli",
    "menu.items.plumTea": "Korean Plum Tea",
    "menu.items.yuzuSoda": "Yuzu Soda",
    "menu.openingHours": "영업 시간",
    "menu.mondayFriday": "월요일 - 금요일",
    "menu.saturdaySunday": "토요일 - 일요일",
    
    // Contact page
    "contact.title": "연락처",
    "contact.getInTouch": "연락하기",
    "contact.address": "주소",
    "contact.email": "이메일",
    "contact.phone": "전화",
    "contact.followUs": "팔로우",
    "contact.reservation": "예약하기",
    "contact.name": "이름",
    "contact.phoneNumber": "전화번호",
    "contact.emailAddress": "이메일 주소",
    "contact.numberOfGuests": "인원 수",
    "contact.dateTime": "날짜 & 시간",
    "contact.date": "날짜",
    "contact.time": "시간",
    "contact.mondayClosed": "월요일 휴무",
    "contact.selectTime": "시간 선택",
    "contact.submit": "예약 제출",
    "contact.submitAlert": "예약 요청이 접수되었습니다. 예약 가능 여부를 확인한 후 최대한 빨리 연락드리겠습니다.",
    "contact.required": "* 모든 필드는 필수입니다",
    "contact.alert":"⚠️ 당일 예약은 온라인으로 불가능합니다!",
    "contact.selectGuests": "인원 선택",
    "contact.guest": "명",
    "contact.guestsPlural": "명",
    "contact.namePlaceholder": "이름을 입력하세요",
    "contact.phonePlaceholder": "+62 xxx xxxx xxxx",
    "contact.emailPlaceholder": "your.email@example.com",
    
    // Footer
    "footer.tagline": "여기에서 우리 회사에 대해 시도해보십시오",
    
    // Days
    "days.tuesday": "화요일",
    "days.friday": "금요일",
    "days.saturday": "토요일",
    "days.sunday": "일요일",
    "days.monday": "월요일",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("en");

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.en] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}